/**
 * Daily Gratitude Prompts - 366 prompts (one for each day of the year including leap years)
 * Organized by month with seasonal themes
 */

export const DAILY_PROMPTS: string[] = [
  // January (Days 1-31): New Beginnings & Fresh Starts
  'What new opportunity are you grateful for today?',
  'What healthy habit are you proud of starting or maintaining?',
  'Who has supported your recovery journey?',
  'What positive change have you noticed in yourself recently?',
  'What small victory can you celebrate today?',
  'What aspect of your morning routine brings you peace?',
  'What lesson from your past are you grateful to have learned?',
  'What natural element (sun, rain, wind) made you feel alive today?',
  'What conversation brought you clarity or comfort?',
  'What do you appreciate about your current living space?',
  'What skill or talent are you developing?',
  'What act of self-care did you practice today?',
  'What boundary have you set that protects your wellbeing?',
  'What makes you feel hopeful about the future?',
  'What book, podcast, or resource has helped your growth?',
  'What physical sensation brought you pleasure today?',
  'What quality in yourself are you learning to appreciate?',
  'What relationship has deepened or improved?',
  'What fear have you faced or overcome?',
  'What brings you a sense of purpose?',
  'What weather today suited your mood perfectly?',
  'What made you smile or laugh today?',
  'What do you appreciate about your body and its healing?',
  'What supportive community or group are you part of?',
  'What mistake taught you something valuable?',
  'What small pleasure did you savor today?',
  'What difficult emotion did you allow yourself to feel?',
  'What progress have you made, no matter how small?',
  'What do you appreciate about this present moment?',
  'What strength have you discovered in yourself?',
  'What are you looking forward to tomorrow?',

  // February (Days 32-59/60): Connection & Relationships
  'Who showed you kindness today?',
  'What quality do you admire in someone close to you?',
  'What conversation deepened your connection with someone?',
  'What did you learn from listening to someone else?',
  'Who makes you feel understood and accepted?',
  'What act of service did you offer or receive?',
  'What relationship in your life is most supportive?',
  'What difficult conversation led to growth?',
  'Who has forgiven you or shown you grace?',
  'What boundary in a relationship has improved it?',
  'What shared experience brought you closer to someone?',
  'Who celebrates your victories with you?',
  'What do you appreciate about your family (chosen or biological)?',
  'Who has taught you something important recently?',
  'What compliment did you receive or give?',
  'What moment of genuine connection did you experience?',
  'Who accepts you exactly as you are?',
  'What act of vulnerability strengthened a relationship?',
  'Who has been patient with you during difficult times?',
  'What do you value most in your friendships?',
  'Who inspires you to be better?',
  'What misunderstanding was cleared up?',
  'Who has listened without judgment?',
  'What collaborative effort brought you joy?',
  'Who has respected your recovery journey?',
  'What trait in yourself helps you connect with others?',
  'Who has offered you hope when you needed it?',
  'What act of compassion touched your heart?',
  'What do you appreciate about being alone sometimes?',
  // Leap year day (Feb 29 - Day 60)
  'What rare or special connection are you grateful for today?',

  // March (Days 60/61-90/91): Growth & Renewal
  'What new growth do you notice in yourself?',
  'What old pattern have you outgrown?',
  'What challenge is helping you become stronger?',
  'What aspect of recovery feels easier now than before?',
  'What new perspective has changed your life?',
  'What wisdom have you gained from difficulty?',
  'What creative expression brings you joy?',
  'What part of yourself are you reclaiming?',
  'What belief about yourself have you changed?',
  'What healing have you experienced?',
  'What are you learning to let go of?',
  'What strength emerged from struggle?',
  'What aspect of yourself are you nurturing?',
  'What transformation are you witnessing?',
  'What truth about yourself are you accepting?',
  'What wound is beginning to heal?',
  'What version of yourself are you becoming?',
  'What possibility excites you now?',
  'What inner resource have you discovered?',
  'What growth required you to be uncomfortable?',
  'What outdated story are you rewriting?',
  'What emerging talent or interest are you exploring?',
  'What part of your identity feels authentic now?',
  'What clarity has replaced confusion?',
  'What courage have you shown recently?',
  'What makes you proud of your journey?',
  'What breakthrough moment stands out?',
  'What new beginning are you embracing?',
  'What internal shift has made external changes possible?',
  "What do you now understand that you didn't before?",
  'What potential do you see in yourself?',

  // April (Days 91/92-120/121): Presence & Mindfulness
  'What did you notice with your senses today?',
  'What moment were you fully present for?',
  'What simple pleasure did you experience?',
  'What brought you back to the present moment?',
  'What beauty did you observe today?',
  'What sound, smell, or texture delighted you?',
  'What breath brought you peace?',
  'What moment of stillness did you find?',
  'What pulled you out of worry about the future?',
  'What helped you release thoughts about the past?',
  'What mindful activity grounded you?',
  'What allowed you to slow down today?',
  'What did you appreciate about right now?',
  'What small detail caught your attention?',
  'What sensory experience was soothing?',
  'What practice helps you stay present?',
  'What moment of awareness shifted your mood?',
  'What did you truly taste or savor today?',
  'What natural sight amazed you?',
  'What present moment was perfect as it was?',
  'What meditation or pause refreshed you?',
  'What distraction did you choose to release?',
  "What bodily sensation reminded you you're alive?",
  'What mundane task became meaningful?',
  'What observation made you smile?',
  'What brought you into your body?',
  'What reminded you that this moment is enough?',
  'What did you notice that you usually overlook?',
  'What peaceful moment did you create?',
  'What invited you to just be?',

  // May (Days 121/122-151/152): Joy & Appreciation
  'What made you feel joyful today?',
  'What brought lightness to your day?',
  'What playful moment did you experience?',
  'What made you feel alive and vibrant?',
  'What simple joy did you rediscover?',
  'What brought a sense of celebration?',
  'What beauty lifted your spirits?',
  'What hobby or activity energized you?',
  'What made you feel grateful to be sober?',
  'What delightful surprise occurred?',
  'What brought out your inner child?',
  'What music, art, or creativity inspired you?',
  'What warm sunshine or spring moment blessed you?',
  'What laughter did you share?',
  'What freedom do you now enjoy?',
  'What color, flower, or bloom caught your eye?',
  'What excitement do you feel?',
  'What brought ease and flow?',
  'What felt effortless and natural?',
  'What new joy have you discovered in recovery?',
  'What playful experiment did you try?',
  'What made you feel youthful?',
  'What optimism fills you?',
  'What dance, movement, or energy felt good?',
  'What brightened your outlook?',
  'What innocence or wonder did you experience?',
  'What celebration of life did you witness?',
  'What felt like a gift today?',
  'What abundance surrounds you?',
  'What sparkle or shine did you notice?',
  'What pure happiness bubbled up?',

  // June (Days 152/153-181/182): Strength & Resilience
  'What strength did you demonstrate today?',
  'What challenge did you face with courage?',
  'What resilience have you developed?',
  'What difficulty did you navigate?',
  'What perseverance are you proud of?',
  'What setback did you recover from?',
  'What enabled you to keep going?',
  'What support helped you through a hard time?',
  'What lesson from adversity are you grateful for?',
  'What did you survive that once seemed impossible?',
  'What inner power did you access?',
  'What weakness became a strength?',
  'What did you overcome today?',
  'What tenacity have you shown?',
  "What reminded you how far you've come?",
  'What made you feel capable?',
  'What helped you bounce back?',
  'What difficult choice showed your strength?',
  'What storm have you weathered?',
  'What warrior spirit emerged?',
  'What grit did you discover?',
  'What helped you endure?',
  'What fight in you are you proud of?',
  'What adversity shaped you for the better?',
  'What determination carried you forward?',
  'What refusal to give up defined you?',
  'What persistence paid off?',
  'What mental toughness did you develop?',
  'What survivor strength do you honor?',
  'What unbreakable part of yourself did you find?',

  // July (Days 182/183-212/213): Freedom & Independence
  'What freedom does sobriety give you?',
  'What independence have you gained?',
  'What liberation do you feel?',
  'What no longer controls you?',
  'What choice do you now have?',
  'What autonomy are you celebrating?',
  'What self-reliance have you developed?',
  'What escape from old patterns are you grateful for?',
  'What agency over your life do you have?',
  'What addiction no longer holds you?',
  'What clear mind do you appreciate?',
  'What self-direction guides you now?',
  'What sovereignty over your decisions brings relief?',
  'What empowerment do you feel?',
  'What release from shame frees you?',
  'What ability to choose differently inspires you?',
  'What freedom to feel do you now have?',
  'What independence from substances sustains you?',
  'What self-determination strengthens you?',
  'What fresh start are you living?',
  'What open road lies ahead?',
  'What limitless potential exists now?',
  'What chains have been broken?',
  'What bright future beckons?',
  'What new life are you claiming?',
  'What possibility replaces limitation?',
  'What expansiveness do you feel?',
  'What own path are you walking?',
  'What self-trust have you earned?',
  'What declaration of independence from old ways are you making?',
  'What authentic self is emerging free?',

  // August (Days 213/214-243/244): Abundance & Gratitude
  'What abundance exists in your life right now?',
  'What overflow of goodness do you notice?',
  'What more-than-enough do you have?',
  'What richness of experience are you grateful for?',
  'What plenty surrounds you?',
  'What fullness of life do you feel?',
  'What harvest are you reaping?',
  'What generosity have you received?',
  'What wealth of relationships do you have?',
  'What sufficiency brings contentment?',
  'What blessings are easy to overlook but worth noticing?',
  'What overflow of support exists?',
  'What multiplying good things do you see?',
  'What prosperity of spirit do you feel?',
  "What riches that aren't material matter most?",
  'What bounty of nature amazes you?',
  'What giving have you been able to do?',
  'What excess of beauty exists around you?',
  'What abundance mindset are you cultivating?',
  'What gratitude multiplies your joy?',
  'What thankfulness opens your heart?',
  'What appreciation deepens your experience?',
  'What recognition of gifts changes your perspective?',
  'What acknowledgment of goodness lifts you?',
  'What counting of blessings soothes you?',
  'What grace have you been shown?',
  'What fortune, despite challenges, do you have?',
  'What lucky breaks have helped you?',
  'What serendipity brought goodness?',
  'What gifts are you now able to receive?',
  'What fullness of heart do you feel?',

  // September (Days 244/245-273/274): Wisdom & Learning
  'What important lesson did you learn today?',
  'What wisdom came from experience?',
  'What insight changed your perspective?',
  'What knowledge are you gaining?',
  'What understanding deepened?',
  'What teaching or teacher are you grateful for?',
  'What book or learning opened your mind?',
  'What realization shifted something?',
  'What awareness grew?',
  'What discovery excited you?',
  'What truth became clear?',
  'What education (formal or informal) helps you?',
  'What mentor or guide has influenced you?',
  'What questioning led to answers?',
  'What curiosity enriched your life?',
  'What mistake became a teacher?',
  'What reflection brought wisdom?',
  'What different viewpoint expanded your thinking?',
  'What patience with learning are you practicing?',
  'What growth in understanding do you notice?',
  'What enlightenment emerged from darkness?',
  'What study or practice is rewarding?',
  'What epiphany occurred?',
  "What sense you're making of things brings peace?",
  'What deeper meaning have you found?',
  'What philosophy or principle guides you?',
  'What intellectual growth are you experiencing?',
  'What question are you exploring?',
  'What knowing (in your gut/heart) are you trusting?',
  'What integration of head and heart is happening?',

  // October (Days 274/275-304/305): Transformation & Change
  'What transformation are you witnessing in yourself?',
  'What change are you embracing?',
  'What evolution is occurring?',
  'What metamorphosis inspires you?',
  'What shift has improved your life?',
  'What transition are you navigating?',
  'What becoming is in progress?',
  'What revolution in thinking has occurred?',
  'What reinvention are you attempting?',
  'What radical change are you grateful for?',
  'What reformation of habits serves you?',
  'What alteration brought relief?',
  'What modification made things better?',
  'What conversion experience changed you?',
  'What rebirth are you experiencing?',
  'What renovation of self is underway?',
  'What dramatic improvement has occurred?',
  'What turning point do you recognize?',
  'What breakthrough transformed things?',
  'What fundamental change sustains recovery?',
  'What different person are you becoming?',
  'What old self are you releasing?',
  'What new self are you welcoming?',
  'What unrecognizable (in a good way) aspects exist now?',
  'What before-and-after amazes you?',
  'What complete turnaround has happened?',
  'What reversed course saved you?',
  'What 180-degree change occurred?',
  'What total transformation gives you hope?',
  'What changed perspective changed everything?',
  'What autumn of old ways makes room for new growth?',

  // November (Days 305/306-334/335): Reflection & Gratitude
  'What are you most grateful for in your recovery?',
  'What person are you thankful for today?',
  'What experience taught you to be grateful?',
  'What challenge are you now thankful for?',
  'What loss led to unexpected gain?',
  'What pain brought eventual wisdom?',
  'What darkness made you appreciate light?',
  'What difficulty revealed strength?',
  'What hardship led to growth?',
  'What journey are you grateful to be on?',
  'What past version of yourself deserves thanks?',
  'What struggle made victory sweeter?',
  'What rock bottom became a foundation?',
  'What ending allowed a new beginning?',
  'What surrender brought peace?',
  'What acceptance brought serenity?',
  'What forgiveness freed you?',
  'What letting go lightened your load?',
  'What release brought relief?',
  'What humble moment taught you?',
  'What grateful heart moment did you have?',
  'What appreciation for the journey do you feel?',
  'What recognition of progress humbles you?',
  'What acknowledgment of help received opens you?',
  'What thanks do you want to express?',
  'What counting of blessings centers you?',
  "What reflection on how far you've come moves you?",
  'What gathering of gratitude warms you?',
  'What harvest of good things do you see?',
  'What thankful spirit are you cultivating?',

  // December (Days 335/336-365/366): Wonder, Hope & Completion
  'What fills you with wonder today?',
  'What miracle (big or small) do you recognize?',
  'What hope sustains you?',
  'What magic in everyday life amazes you?',
  'What mysterious goodness touches you?',
  'What awe do you feel?',
  'What marvel of recovery inspires you?',
  'What extraordinary in the ordinary do you see?',
  'What spectacular moment occurred?',
  'What phenomenal progress have you made?',
  'What remarkable journey are you on?',
  'What wonderful surprise delighted you?',
  'What hopeful future do you envision?',
  'What promise does tomorrow hold?',
  'What optimism fills your heart?',
  'What expectation of good things is reasonable?',
  'What faith in your recovery do you have?',
  'What confidence in your path grows?',
  'What trust in the process sustains you?',
  'What belief in better days ahead helps you?',
  'What completion of a cycle do you recognize?',
  'What achievement of a goal happened?',
  'What finish line did you cross?',
  'What wholeness are you approaching?',
  "What integration of all you've learned is occurring?",
  'What full circle moment amazes you?',
  'What conclusion brings satisfaction?',
  'What culmination of effort pays off?',
  'What fulfillment do you feel?',
  "What readiness for what's next exists?",
  'What perfect ending and new beginning are you grateful for?',
];

/**
 * Get the prompt for a specific day of the year (1-366)
 */
export function getPromptForDay(dayOfYear: number): string {
  // Ensure day is within valid range
  const day = Math.max(1, Math.min(366, dayOfYear));
  return DAILY_PROMPTS[day - 1]; // Array is 0-indexed, days are 1-indexed
}

/**
 * Get the current day of the year (1-366)
 */
export function getCurrentDayOfYear(): number {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  return Math.floor(diff / oneDay);
}

/**
 * Get today's prompt
 */
export function getTodaysPrompt(): string {
  return getPromptForDay(getCurrentDayOfYear());
}
